import axios from "axios";
import Head from "next/head";
import Image from "next/image";

export default function Home({ characters }) {
  return (
    <div>
      <Head>
        <title>Breaking Bad</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className="p-10"
        className="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 lg:grid-cols-3 xl:grid-cols-4 gap-5"
      >
        {characters.map((char) => (
          <div className=" rounded overflow-hidden shadow-lg" key={char.id}>
            <div className="relative h-[400px]">
              <Image
                className="w-full"
                src={char.img}
                alt="Mountain"
                layout="fill"
                objectFit="contain"
              />
            </div>
            <div className="px-6 py-4">
              <div className="font-bold text-xl mb-2">{char.name}</div>
              <p className="text-gray-700 text-base">{char.nickname}</p>
            </div>
            <div className="px-6 pt-4 pb-2">
              <span className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                #photography
              </span>
              <span className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                #travel
              </span>
              <span className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">
                #winter
              </span>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

export const getStaticProps = async (context) => {
  const characters = await axios
    .get("https://www.breakingbadapi.com/api/characters")
    .then((res) => res.data);
  return {
    props: {
      characters,
    },
  };
};
