import axios from "axios";
import Head from "next/head";

export default function Home({ characters }) {
  return (
    <div>
      <Head>
        <title>Breaking Bad</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ul>
        {characters.map((char) => (
          <li key={char.id}>{char.name}</li>
        ))}
      </ul>
    </div>
  );
}

export const getStaticProps = async (context) => {
  const characters = await axios
    .get("https://www.breakingbadapi.com/api/characters")
    .then((res) => res.data);
  return {
    props: {
      characters,
    },
  };
};
